/* Built at 2013-08-10 04:09:15 +0200 */
var unite=function(c){function f(a,g,d){var h=a.querySelectorAll("*");c.log("binding.scope: ",d.scope,", elements: ",h.length,", content",d.content);c.applyAttributes(a,d.attributes,d,g);c.applyText(a,g,d);for(a=0;a<h.length;a++){var q=c.attributesWithVariables(h[a]);c.applyText(h[a],g,d);c.applyAttributes(h[a],q,d,g)}}function b(a){for(var g=[],d=0;d<c.bindings.length;d++)-1!=c.bindings[d].variables.indexOf(a)&&g.push(c.bindings[d]);return g}function e(a,g,d){for(var h=a.loop_id,q=[],b=a.parentNode.querySelectorAll("*"),
e=0;e<b.length;e++)b[e].looped_id==h&&q.push(b[e]);for(var h=0,m;h<q.length;)a.parentNode.removeChild(q[h]),h+=1;for(e=0;g&&e<g.length;e++){var k=g[e];c.isObject(k)||(k={},k["this"]=g[e],k._index=e,k._human_index=e+1);h<q.length?(b=q[h],f(b,k,d),h+=1):(b=d.tpl_element.cloneNode(),b.innerHTML=d.tpl_element.innerHTML,b.looped_id=a.loop_id,f(b,k,d),m?m.parentNode.insertBefore(b,m.nextSibling):a.parentNode.insertBefore(b,a.nextSibling));m=b}for(;h<q.length;)a.parentNode.removeChild(q[h]),h+=1}function m(a,
g){var d=[],h=[],b="",e=k(a);e&&(b=e.match(c.variable_regexp));b&&(h=h.concat(b));for(e=0;e<a.attributes.length;e++)(b=a.attributes[e].nodeValue.match(c.variable_regexp))&&(h=h.concat(b));for(e=0;e<h.length;e++)b=h[e].replace(c.variable_regexp,function(a,c){return c}),"_index"!=b&&("_human_index"!=b&&"this"!=b)&&d.push(g+"."+b);for(e=0;e<a.attributes.length;e++)h=a.attributes[e].nodeName,b=a.attributes[e].nodeValue,"scope"==h||"loop"==h?d.push(g):"event"==h&&d.push(g+"."+b);return d}function k(a){if((a=
a.childNodes[0])&&3==a.nodeType)return a.nodeValue}function l(a){if(a){var g,d,h=a.split("..");1<h.length&&(a=h[h.length-1]);h=a.split(".");g=window[h[0]];for(var b=1;void 0!==g&&b<h.length;b++){d=g;a=g[h[b]];if("()"==h[b].slice(-2)){var e=h[b].replace("()","");try{a=g[e]()}catch(m){console.log(m)}c.log("EXECUTE FUNCTION: ",h[b])}if(b==h.length-1)return c.isFunction(a)&&(a=a.bind(d)),a;c.isFunction(a)||(g=a)}return g}}var u={SELECT:["change"],INPUT:["change"],BUTTON:["click","touchend"],A:["click",
"touchend"]};c.variable_regexp=/{{([\w\.\(\)]+)}}/gi;c.render=function(a){a||(a={});var g=c.document.documentElement.innerHTML;a.normalize&&(g=g.replace(/\;"/,'"'));return g};c.init=function(a,g){void 0===g&&(g={render:!0});var d;c.debug="1"==c.urlParameters().debug;c.variable_content={};c.bindings=[];c.isString(a)?(c.document=document.implementation.createHTMLDocument(""),c.document.documentElement.innerHTML=a):c.document=document;d=c.document.querySelectorAll("*");for(var b=c,e=[],k=0;k<d.length;k++){var f=
d[k],l=c.attributesWithVariables(f),s;s=(s=f.childNodes[0])&&3==s.nodeType&&s.nodeValue.match(c.variable_regexp)?s.nodeValue:void 0;var n;a:{n=f;var r=[],p=n.getAttribute("scope");if(p){if("."==p[0]){n=void 0;break a}r=[p]}for(n=n.parentNode;n.getAttribute;)(p=n.getAttribute("scope"))&&r.push(p),n=n.parentNode;n=0<r.length?r.reverse().join("."):void 0}r=m(f,n);if(0<r.length){for(p=0;p<r.length;p++)c.variable_content[r[p]]="";var u=f.getAttribute("event"),p=f.getAttribute("loop"),t=null,l={element:f,
scope:n,event:u,attributes:l,variables:r,content:s};p&&(f.loop_id=Math.floor(4294967296*Math.random()).toString(16)+Math.floor(4294967296*Math.random()).toString(16),t=f.cloneNode(),t.innerHTML=f.innerHTML,t.loop_id=f.loop_id,t.removeAttribute("loop"),l.tpl_element=t,l.loop=p,f.style.display="none");e.push(l)}}b.bindings=e.reverse();!1!=g.render&&c.applyDirty();return this};c.update=function(){c.applyDirty()};c.apply=function(a){var g=a.element.tagName;c.log("*** Apply() "+g+": "+a.scope+" -> "+(c.isArray(b)?
"array":c.isFunction(b)?"function":c.isString(b)?"string":c.isNumber(b)?"number":"object"));(b=u[g])||(b=["click"]);if(a.event&&a.loop){c.log("event + loop for "+g);var d=l(a.scope+"."+a.event);c.addEvent(a.element.parentNode,b,function(a){d(a);c.update()});var b=l(a.scope+"."+a.loop);e(a.element,b,a)}else a.event&&!a.loop?(d=l(a.scope+"."+a.event),c.addEvent(a.element,b,function(a){d(a);c.update()})):!a.event&&a.loop&&(b=l(a.scope+"."+a.loop),e(a.element,b,a));b=l(a.scope);f(a.element,b,a)};c.applyAttributes=
function(a,b,d,e){for(var f=0;f<b.length;f++)for(var k in b[f]){var m=b[f][k].replace(c.variable_regexp,function(a,b){if(void 0!==e[b])return e[b];var c=l(d.scope+"."+b);return void 0!==c?c:a});"data-style"==k?(a.removeAttribute(k),a.setAttribute("style",m)):a.setAttribute(k,m)}};c.applyText=function(a,b,d){(a=a.childNodes[0])&&3==a.nodeType&&(a.nodeValue=(d.content||a.nodeValue).replace(c.variable_regexp,function(a,e){if(void 0!==b[e])return c.log("applyText(): ",e," -> ",b[e]),b[e];var f=d.scope+
"."+e;c.log("applyText(): ",f," -> "+l(f));f=l(f);return void 0!==f?f:a}))};c.applyDirty=function(){c.log("*** applyDirty()");for(var a in c.variable_content)if(c.isDirty(a,c.variable_content[a])){var g=l(a);c.log("--- Variable has changed: ",a,": ",c.variable_content[a]," -> ",g);c.variable_content[a]=c.clone(g);g=b(a);c.log("Found "+g.length+" bindings to apply");for(var d=0;d<g.length;d++)c.apply(g[d])}c.log("*** applyDirty() END")};c.applyAll=function(){for(var a in c.variable_content)for(var g=
b(a),d=0;d<g.length;d++)c.apply(g[d])};c.clone=function(a){return c.isArray(a)?a.slice(0):c.isObject(a)?JSON.parse(JSON.stringify(a)):a};c.isDirty=function(a,b){var d=l(a);return b||d?!b&&d||b&&!d?!0:c.isFunction(b)&&c.isFunction(d)?b.toString()!=d.toString():void 0!==b.length&&void 0!==d.length&&b.length!=d.length||JSON.stringify(b)!=JSON.stringify(d)||JSON.stringify(b)!=JSON.stringify(d)&&b!=d?!0:!1:!1};c.addEvent=function(a,b,d,e){c.log("AddEvent() "+a.tagName+" - "+b);if(c.isArray(b))for(var f=
0;f<b.length;f++)c.addEvent(a,b[f],d,e);else a.addEventListener?a.addEventListener(b,d,e):a.attachEvent?(a["e"+b+d]=d,a[b+d]=function(){a["e"+b+d](window.event)},a.attachEvent("on"+b,a[b+d])):a["on"+b]=a["e"+b+d]};c.attributesWithVariables=function(a){for(var b=[],d=0;d<a.attributes.length;d++){var e=a.attributes[d];if(e.nodeValue.match(c.variable_regexp)){var f={};f[e.nodeName]=e.nodeValue;b.push(f)}}return b};c.urlParameters=function(){for(var a={},b,c=window.location.href.slice(window.location.href.indexOf("?")+
1).split("&"),e=0;e<c.length;e++)b=c[e].split("="),a[b[0]]=b[1];return a};c.log=function(){if(c.debug){for(var a="",b=0;b<arguments.length;b++)var e=arguments[b],a=c.isString(e)?a+e:c.isObject(e)?a+JSON.stringify(e):void 0===e?a+"undefined":a+e.toString();console?console.log(a):alert(a)}};c.isString=function(a){return"string"==typeof a};c.isObject=function(a){return null!=a&&"object"==typeof a};c.isArray=function(a){return void 0===a?!1:-1!=a.constructor.toString().indexOf("Array")};c.isFunction=
function(a){return"[object Function]"===Object.prototype.toString.call(a)};c.isNumber=function(a){return!isNaN(a)};Array.prototype.indexOf||(Array.prototype.indexOf=function(a){for(var b=-1,c=0;c<this.length;c++)if(this[c]===a){b=c;break}return b});Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,e=function(){},f=
function(){return c.apply(this instanceof e&&a?this:a,b.concat(Array.prototype.slice.call(arguments)))};e.prototype=this.prototype;f.prototype=new e;return f});return c}(unite||{});"use strict";
var last_click,unite=function(c){var f=this;c.router={routes:[],regexp_routes:[],variable_regexp:/:([\w]+)/ig,scrolling:!1,init:function(b){f=this;this.routes=b;this.regexp_routes=this.createRegexpRoutes(this.routes);b=document.getElementsByTagName("body")[0];c.addEvent(b,"touchstart",function(b){f.scrolling=!1},!1);c.addEvent(b,"touchmove",function(b){f.scrolling=!0},!1);c.addEvent(b,"touchend",this.touchHandler,!0);c.addEvent(window,"popstate",this.popStateHandler,!0);c.addEvent(b,"click",this.clickHandler,
!0)},popStateHandler:function(b){b.state&&f.dispatch(b.state.url,!1)},touchHandler:function(b){f.scrolling||f.skipClick||(f.clickHandler(b),f.skipClick=!0,setTimeout(function(){f.skipClick=!1},300))},clickHandler:function(b){if(!f.skipClick){f.skipClick=!0;setTimeout(function(){f.skipClick=!1},300);for(var c=b.target||b.srcElement;c.getAttribute&&null==c.getAttribute("href")||"A"!=c.tagName&&"BUTTON"!=c.tagName;)if(c=c.parentNode,!c)return;c&&c.getAttribute&&(c=c.getAttribute("href"),0!=c.indexOf("http")&&
(f.dispatch(c,!0),b.cancelBubble=!0,b.returnValue=!1,b.stopPropagation&&b.stopPropagation(),b.preventDefault&&b.preventDefault()))}},dispatch:function(b,e){void 0===e&&(e=!0);b||(b=window.location.pathname);console.log(">> Dispatching route "+b);var m=f.match(b);if(m&&(c.log(m),m.action)){history&&(history.pushState&&e)&&(console.log("pushState "+b),history.pushState({url:b},window.title,b));var k=f.getScopedVariable(m.action);k[1].call(k[0],m.params);c.update()}},getScopedVariable:function(b){if(b){var c,
f=b.split(".");b=window[f[0]];for(var k=1;b&&k<f.length;k++)c=b,b=b[f[k]];return[c,b]}},match:function(b){if(b){for(var c in this.routes)if(c==b)return{url:b,action:this.routes[c],params:{}};for(var f=0;f<this.regexp_routes.length;f++){c=this.regexp_routes[f];var k=b.match(c.regexp);if(k&&0<k.length){k.shift();for(var f={},l=0;l<c.parameters.length;l++)f[c.parameters[l]]=k[l];return{url:b,action:c.action,params:f}}}}},createRegexpRoutes:function(b){b=[];for(var c in this.routes){var f=[],k=c.replace(this.variable_regexp,
function(b,c){f.push(c);return"([\\w]+)"});0<f.length&&(k=k.replace(/\//g,"\\/"),k=RegExp(k,"i"),c={url:c,regexp:k,parameters:f,action:this.routes[c]},b.push(c))}return b}};return c}(unite||{});unite.addEvent(window,"load",function(){unite.init();if(unite.onload)unite.onload()},!1);
