/* Built at 2013-07-24 22:51:08 +0200 */
var unite=function(b){function p(a,c,d){var e=a.querySelectorAll("*");b.applyAttributes(a,d.attributes,d,c);b.applyText(a,c,d);for(a=0;a<e.length;a++){var g=b.attributesWithVariables(e[a]);b.applyText(e[a],c,d);b.applyAttributes(e[a],g,d,c)}}function s(a,c,d){console.log("loopElement");for(var e=a.loop_id,g=[],f=a.parentNode.querySelectorAll("*"),h=0;h<f.length;h++)f[h].looped_id==e&&g.push(f[h]);var e=0,k;console.log("Found "+g.length+" reusable elements");for(h=0;c&&h<c.length;h++){var l=c[h];b.isObject(l)||
(l={},l["this"]=c[h],l._index=h,l._human_index=h+1);e<g.length?(f=g[e],p(f,l,d),e+=1):(f=d.tpl_element.cloneNode(),f.innerHTML=d.tpl_element.innerHTML,f.looped_id=a.loop_id,p(f,l,d),k?k.parentNode.insertBefore(f,k.nextSibling):a.parentNode.insertBefore(f,a.nextSibling));k=f}for(;e<g.length;)a.parentNode.removeChild(g[e]),e+=1}function u(a,c){var d=[],e=[],g="",f=v(a);f&&(g=f.match(b.variable_regexp));g&&(e=e.concat(g));for(f=0;f<a.attributes.length;f++)(g=a.attributes[f].nodeValue.match(b.variable_regexp))&&
(e=e.concat(g));for(f=0;f<e.length;f++)g=e[f].replace(b.variable_regexp,function(a,c){return c}),"_index"!=g&&("_human_index"!=g&&"this"!=g)&&d.push(c+"."+g);for(f=0;f<a.attributes.length;f++)e=a.attributes[f].nodeName,g=a.attributes[f].nodeValue,"scope"==e||"loop"==e?d.push(c):"action"==e&&d.push(c+"."+g);return d}function v(a){if((a=a.childNodes[0])&&3==a.nodeType)return a.nodeValue}function k(a,c){if(a){var d,e,g,f=a.split(".");e=window[f[0]];for(var h=1;e&&h<f.length;h++){g=e;d=e[f[h]];"()"==
f[h].slice(-2)&&(d=f[h].replace("()",""),d=e[d](),console.log("EXECUTE FUNCTION: "+f[h]));if(h==f.length-1)return b.isFunction(d)&&(d=d.bind(g)),d;b.isFunction(d)||(e=d)}return e}}function q(a){q="function"===typeof Array.prototype.indexOf?Array.prototype.indexOf:function(a){for(var d=-1,b,d=0;d<this.length;d++)if(this[d]===a){b=d;break}return b};return q.call(this,a)}var t={SELECT:"change",INPUT:"change",BUTTON:"click",DIV:"click",A:"click"};b.variable_regexp=/{{([\w\.\(\)]+)}}/gi;b.render=function(){return b.document.documentElement.innerHTML};
b.init=function(a,c){void 0===c&&(c={render:!0});var d;b.variable_content={};b.bindings=[];b.isString(a)?(b.document=document.implementation.createHTMLDocument(),b.document.documentElement.innerHTML=a):b.document=document;d=b.document.querySelectorAll("*");for(var e=b,g=[],f=0;f<d.length;f++){var h=d[f],k=b.attributesWithVariables(h),l;l=(l=h.childNodes[0])&&3==l.nodeType&&l.nodeValue.match(b.variable_regexp)?l.nodeValue:void 0;var m;a:{m=h;var r=[],n=m.getAttribute("scope");if(n){if(-1!=n.indexOf("window.")){m=
void 0;break a}r=[n]}for(m=m.parentNode;m.getAttribute;)(n=m.getAttribute("scope"))&&r.push(n),m=m.parentNode;m=0<r.length?r.reverse().join("."):void 0}r=u(h,m);if(0<r.length){for(n=0;n<r.length;n++)b.variable_content[r[n]]="";var q=h.getAttribute("action"),n=h.getAttribute("loop"),p=null,k={element:h,scope:m,action:q,attributes:k,variables:r,content:l};n&&(h.loop_id=Math.floor(4294967296*Math.random()).toString(16)+Math.floor(4294967296*Math.random()).toString(16),p=h.cloneNode(),p.innerHTML=h.innerHTML,
p.loop_id=h.loop_id,p.removeAttribute("loop"),k.tpl_element=p,k.loop=n,h.style.display="none");g.push(k)}}e.bindings=g.reverse();!1!=c.render&&b.applyDirty();return this};b.update=function(){console.log("========== UPDATE");b.applyDirty()};b.apply=function(a){var c=a.element.tagName;console.log("Apply() "+c+": "+a.scope+" -> "+(b.isArray(e)?"array":b.isFunction(e)?"function":b.isString(e)?"string":b.isNumber(e)?"number":"object"));if(a.action&&a.loop){console.log("action + loop for "+c);var d=k(a.scope+
"."+a.action);(c=t[c])||(c="click");b.addEvent(a.element.parentNode,c,function(a){var c=a.target||a.srcElement;console.log("EVENT_HANDLER!!");console.log(a);d(c);b.update()});var e=k(a.scope+"."+a.loop);s(a.element,e,a)}else a.action&&!a.loop?(d=k(a.scope+"."+a.action),(c=t[c])||(c="click"),b.addEvent(a.element,c,function(){d();b.update()})):!a.action&&a.loop?(e=k(a.scope+"."+a.loop),s(a.element,e,a)):(e=k(a.scope),p(a.element,e,a))};b.applyAttributes=function(a,c,d,e){for(var g=0;g<c.length;g++)for(var f in c[g]){var h=
c[g][f].replace(b.variable_regexp,function(a,c){if(void 0!==e[c])return e[c];var b=k(d.scope+"."+c);return b?b:a});a.setAttribute(f,h)}};b.applyText=function(a,c,d){(a=a.childNodes[0])&&3==a.nodeType&&(a.nodeValue=(d.content||a.nodeValue).replace(b.variable_regexp,function(a,b){if(void 0!==c[b])return console.log("applyElement(): "+b+" -> "+c[b]),c[b];var f=d.scope+"."+b;console.log("applyElement(): "+f+" -> "+k(f));return(f=k(f))?f:a}))};b.applyDirty=function(){for(var a in b.variable_content)if(b.isDirty(a,
b.variable_content[a])){var c=k(a);console.log("Variable has changed: "+a+": "+b.variable_content[a]+" -> "+c);b.variable_content[a]=b.clone(c);for(var c=a,d=[],e=0;e<b.bindings.length;e++)-1!=q.call(b.bindings[e].variables,c)&&d.push(b.bindings[e]);c=d;for(d=0;d<c.length;d++)b.apply(c[d])}};b.clone=function(a){return b.isArray(a)?a.slice(0):b.isObject(a)?JSON.parse(JSON.stringify(a)):a};b.isDirty=function(a,c){var d=k(a);if(!c&&!d)return!1;if(!c&&d||c&&!d)return!0;if(b.isFunction(c)&&b.isFunction(d))return c.toString()!=
d.toString();if(void 0!==c.length&&void 0!==d.length){if(c.length!=d.length)return!0}else if(JSON.stringify(c)!==JSON.stringify(d)&&c!=d)return!0;return!1};b.addEvent=function(a,c,b){console.log("addEvent(): "+a.tagName+" on"+c);a.addEventListener?a.addEventListener(c,b):a.attachEvent?(a["e"+c+b]=b,a[c+b]=function(){a["e"+c+b](window.event)},a.attachEvent("on"+c,a[c+b])):a["on"+c]=a["e"+c+b]};b.attributesWithVariables=function(a){for(var c=[],d=0;d<a.attributes.length;d++){var e=a.attributes[d];if(e.nodeValue.match(b.variable_regexp)){var g=
{};g[e.nodeName]=e.nodeValue;c.push(g)}}return c};b.isString=function(a){return"string"==typeof a};b.isObject=function(a){return null!=a&&"object"==typeof a};b.isArray=function(a){return void 0===a?!1:-1!=a.constructor.toString().indexOf("Array")};b.isFunction=function(a){return"[object Function]"===Object.prototype.toString.call(a)};b.isNumber=function(a){return!isNaN(a)};return b}(unite||{});window.onload=function(){unite.init()};"use strict";
unite=function(b){function p(a){var b=(a.target||a.srcElement).getAttribute("href");b&&(console.log("* ROUTER CLICK: "+b),console.log("* ROUTER MATCH: "),console.log(s(b)),console.log("* REGEXP ROUTER MATCH: "),console.log(u(b)),a.preventDefault(),a.stopPropagation())}function s(a){for(var b in k)if(b==a)return{action:k[b],params:{}}}function u(a){for(var b in q)if(a.match(b.regexp))return{action:b.action,params:b.parametrers}}function v(a){var b=[],d;for(d in a){var e=[],g=d.replace(t,function(a,
b){e.push(b);return"([\\w+])"});d={url:d,regexp:g,parameters:e,action:a[d]};b.push(d);console.log(d);return d}}var k,q=[],t=/(:[\w]+)/ig;b.debug_routes=function(){console.log(k);console.log(q)};b.route=function(a){k=a;q=v(k);a=document.getElementsByTagName("body")[0];b.addEvent(a,"click",p)};return b}(unite||{});
