/* Built at 2013-07-26 05:48:11 +0200 */
var unite=function(a){function m(b,h,d){var e=b.querySelectorAll("*");a.log("binding.scope: ",d.scope,", elements: ",e.length,", content",d.content);a.applyAttributes(b,d.attributes,d,h);a.applyText(b,h,d);for(b=0;b<e.length;b++){var q=a.attributesWithVariables(e[b]);a.applyText(e[b],h,d);a.applyAttributes(e[b],q,d,h)}}function c(b,h,d){for(var e=b.loop_id,q=[],k=b.parentNode.querySelectorAll("*"),c=0;c<k.length;c++)k[c].looped_id==e&&q.push(k[c]);var e=0,f;a.log(">> loopElement() .. found ",q.length,
" reusable elements");for(c=0;h&&c<h.length;c++){var g=h[c];a.isObject(g)||(g={},g["this"]=h[c],g._index=c,g._human_index=c+1);e<q.length?(k=q[e],m(k,g,d),e+=1):(k=d.tpl_element.cloneNode(),k.innerHTML=d.tpl_element.innerHTML,k.looped_id=b.loop_id,m(k,g,d),f?f.parentNode.insertBefore(k,f.nextSibling):b.parentNode.insertBefore(k,b.nextSibling));f=k}for(;e<q.length;)b.parentNode.removeChild(q[e]),e+=1}function f(b,h){var d=[],e=[],c="",k=l(b);k&&(c=k.match(a.variable_regexp));c&&(e=e.concat(c));for(k=
0;k<b.attributes.length;k++)(c=b.attributes[k].nodeValue.match(a.variable_regexp))&&(e=e.concat(c));for(k=0;k<e.length;k++)c=e[k].replace(a.variable_regexp,function(b,a){return a}),"_index"!=c&&("_human_index"!=c&&"this"!=c)&&d.push(h+"."+c);for(k=0;k<b.attributes.length;k++)e=b.attributes[k].nodeName,c=b.attributes[k].nodeValue,"scope"==e||"loop"==e?d.push(h):"action"==e&&d.push(h+"."+c);return d}function l(b){if((b=b.childNodes[0])&&3==b.nodeType)return b.nodeValue}function g(b,h){if(b){var d,e,
c,k=b.split(".");e=window[k[0]];for(var f=1;e&&f<k.length;f++){c=e;d=e[k[f]];"()"==k[f].slice(-2)&&(d=k[f].replace("()",""),d=e[d](),a.log("EXECUTE FUNCTION: ",k[f]));if(f==k.length-1)return a.isFunction(d)&&(d=d.bind(c)),d;a.isFunction(d)||(e=d)}return e}}function s(b){s="function"===typeof Array.prototype.indexOf?Array.prototype.indexOf:function(b){for(var a=-1,e,a=0;a<this.length;a++)if(this[a]===b){e=a;break}return e};return s.call(this,b)}var u={SELECT:"change",INPUT:"change",BUTTON:"click",
DIV:"click",A:"click"};a.variable_regexp=/{{([\w\.\(\)]+)}}/gi;a.render=function(){return a.document.documentElement.innerHTML};a.init=function(b,h){void 0===h&&(h={render:!0});var d;a.debug="1"==a.urlParameters().debug;a.variable_content={};a.bindings=[];a.isString(b)?(a.document=document.implementation.createHTMLDocument(),a.document.documentElement.innerHTML=b):a.document=document;d=a.document.querySelectorAll("*");for(var e=a,c=[],k=0;k<d.length;k++){var g=d[k],l=a.attributesWithVariables(g),
r;r=(r=g.childNodes[0])&&3==r.nodeType&&r.nodeValue.match(a.variable_regexp)?r.nodeValue:void 0;var n;a:{n=g;var m=[],p=n.getAttribute("scope");if(p){if(-1!=p.indexOf("window.")){n=void 0;break a}m=[p]}for(n=n.parentNode;n.getAttribute;)(p=n.getAttribute("scope"))&&m.push(p),n=n.parentNode;n=0<m.length?m.reverse().join("."):void 0}m=f(g,n);if(0<m.length){for(p=0;p<m.length;p++)a.variable_content[m[p]]="";var s=g.getAttribute("action"),p=g.getAttribute("loop"),t=null,l={element:g,scope:n,action:s,
attributes:l,variables:m,content:r};p&&(g.loop_id=Math.floor(4294967296*Math.random()).toString(16)+Math.floor(4294967296*Math.random()).toString(16),t=g.cloneNode(),t.innerHTML=g.innerHTML,t.loop_id=g.loop_id,t.removeAttribute("loop"),l.tpl_element=t,l.loop=p,g.style.display="none");c.push(l)}}e.bindings=c.reverse();!1!=h.render&&a.applyDirty();return this};a.update=function(){a.applyDirty()};a.apply=function(b){var h=b.element.tagName;a.log("Apply() "+h+": "+b.scope+" -> "+(a.isArray(e)?"array":
a.isFunction(e)?"function":a.isString(e)?"string":a.isNumber(e)?"number":"object"));if(b.action&&b.loop){a.log("action + loop for "+h);var d=g(b.scope+"."+b.action);(h=u[h])||(h="click");a.addEvent(b.element.parentNode,h,function(b){var h=b.target||b.srcElement;console.log("!! Event Handler: "+b);d(h);a.update()});var e=g(b.scope+"."+b.loop);c(b.element,e,b)}else b.action&&!b.loop?(d=g(b.scope+"."+b.action),(h=u[h])||(h="click"),a.addEvent(b.element,h,function(){d();a.update()})):!b.action&&b.loop?
(e=g(b.scope+"."+b.loop),c(b.element,e,b)):(e=g(b.scope),m(b.element,e,b))};a.applyAttributes=function(b,h,d,e){for(var c=0;c<h.length;c++)for(var f in h[c]){var l=h[c][f].replace(a.variable_regexp,function(b,a){if(void 0!==e[a])return e[a];var h=g(d.scope+"."+a);return h?h:b});b.setAttribute(f,l)}};a.applyText=function(b,h,d){(b=b.childNodes[0])&&3==b.nodeType&&(b.nodeValue=(d.content||b.nodeValue).replace(a.variable_regexp,function(b,c){if(void 0!==h[c])return a.log("applyElement(): ",c," -> ",
h[c]),h[c];var f=d.scope+"."+c;a.log("applyElement(): ",f," -> "+g(f));return(f=g(f))?f:b}))};a.applyDirty=function(){for(var b in a.variable_content)if(a.isDirty(b,a.variable_content[b])){var c=g(b);a.log("Variable has changed: ",b,": ",a.variable_content[b]," -> ",c);a.variable_content[b]=a.clone(c);for(var c=b,d=[],e=0;e<a.bindings.length;e++)-1!=s.call(a.bindings[e].variables,c)&&d.push(a.bindings[e]);c=d;for(d=0;d<c.length;d++)a.apply(c[d])}};a.clone=function(b){return a.isArray(b)?b.slice(0):
a.isObject(b)?JSON.parse(JSON.stringify(b)):b};a.isDirty=function(b,c){var d=g(b);if(!c&&!d)return!1;if(!c&&d||c&&!d)return!0;if(a.isFunction(c)&&a.isFunction(d))return c.toString()!=d.toString();if(void 0!==c.length&&void 0!==d.length){if(c.length!=d.length)return!0}else if(JSON.stringify(c)!==JSON.stringify(d)&&c!=d)return!0;return!1};a.addEvent=function(b,a,c,e){b.addEventListener?b.addEventListener(a,c,e):b.attachEvent?(b["e"+a+c]=c,b[a+c]=function(){b["e"+a+c](window.event)},b.attachEvent("on"+
a,b[a+c])):b["on"+a]=b["e"+a+c]};a.attributesWithVariables=function(b){for(var c=[],d=0;d<b.attributes.length;d++){var e=b.attributes[d];if(e.nodeValue.match(a.variable_regexp)){var f={};f[e.nodeName]=e.nodeValue;c.push(f)}}return c};a.urlParameters=function(){for(var b={},a,c=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),e=0;e<c.length;e++)a=c[e].split("="),b[a[0]]=a[1];return b};a.log=function(){if(a.debug){for(var b="",c=0,d;d=arguments[c];c++)b=a.isString(d)?b+d:a.isObject(d)?
b+JSON.stringify(d):b+d.toString();console?console.log(b):alert(b)}};a.isString=function(b){return"string"==typeof b};a.isObject=function(b){return null!=b&&"object"==typeof b};a.isArray=function(b){return void 0===b?!1:-1!=b.constructor.toString().indexOf("Array")};a.isFunction=function(b){return"[object Function]"===Object.prototype.toString.call(b)};a.isNumber=function(b){return!isNaN(b)};return a}(unite||{});window.onload=function(){unite.init()};"use strict";
var last_click,unite=function(a){var m=this;a.router={routes:[],regexp_routes:[],variable_regexp:/:([\w]+)/ig,init:function(c){m=this;this.routes=c;this.regexp_routes=this.createRegexpRoutes(this.routes);c=document.getElementsByTagName("body")[0];a.addEvent(c,"click",this.clickHandler,!0);a.addEvent(window,"popstate",this.popStateHandler,!0)},popStateHandler:function(a){m.dispatch(event.url)},clickHandler:function(a){for(var f=a.target||a.srcElement;f.getAttribute&&null==f.getAttribute("href")||"A"!=
f.tagName;)if(f=f.parentNode,!f)return;f&&f.getAttribute&&(f=f.getAttribute("href"),m.dispatch(f));a.stopPropagation();a.preventDefault()},dispatch:function(c){c||(c="/");var f=m.match(c);if(f&&(a.log(f),f.action)){var l=m.getScopedVariable(f.action);l[1].call(l[0],f.params);a.update();history&&history.pushState({url:c},window.title,c)}},getScopedVariable:function(a){if(a){var f,l=a.split(".");a=window[l[0]];for(var g=1;a&&g<l.length;g++)f=a,a=a[l[g]];return[f,a]}},match:function(a){if(a){for(var f in this.routes)if(f==
a)return{url:a,action:this.routes[f],params:{}};for(var l=0;l<this.regexp_routes.length;l++){f=this.regexp_routes[l];var g=a.match(f.regexp);if(g&&0<g.length){g.shift();for(var l={},m=0;m<f.parameters.length;m++)l[f.parameters[m]]=g[m];return{url:a,action:f.action,params:l}}}}},createRegexpRoutes:function(a){a=[];for(var f in this.routes){var l=[],g=f.replace(this.variable_regexp,function(a,c){l.push(c);return"([\\w]+)"});0<l.length&&(g=g.replace(/\//g,"\\/"),g=RegExp(g,"i"),f={url:f,regexp:g,parameters:l,
action:this.routes[f]},a.push(f))}return a}};return a}(unite||{});
